CREATE TABLE PUBLIC.user_table
(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  rank INT DEFAULT 1000 NOT NULL
);
ALTER TABLE PUBLIC.user_table ADD CONSTRAINT unique_username UNIQUE (username);